// describe('Adding flight', () => {
//   it('adding Special Uplift', () => {
//     cy.visit(' https://itxi-recruiter-extract.web.app/login')
//     cy.get('input[type="email"]').type("qaquiz@gmail.com")
//     cy.get('input[type="password"]').type("Test@123")
//     cy.contains('Login').click()
//     cy.wait(2000)
//     cy.contains("Special Uplift").click()
//     cy.wait(2500)
//     cy.get('input[role="combobox"]').click()
//     cy.contains("2023-03-29 | 17:35 | ME0267 | BEY → IST").click()
//     cy.get('input[id="passengerName"]').type("Mohammad Jaafar")
//     cy.get('input[id="offeredBy"]').type("Nadine")
//     cy.get('textarea[id="additionalNotes"]').type("Seat next Window")
//     cy.get('input[role="combobox"]').click()
//     cy.contains('Wedding Cake').click()
//     cy.contains("Credit Card").click()
//     cy.contains("Received").click()
//     cy.contains("Save").click()
//   })
// })

describe('Adding flight', () => {
  it('adding Preorder Saleable', () => {
    cy.visit(' https://itxi-recruiter-extract.web.app/login')
    cy.get('input[type="email"]').type("qaquiz@gmail.com")
    cy.get('input[type="password"]').type("Test@123")
    cy.contains('Login').click()
    cy.wait(2000)
    cy.contains("Pre-order Saleable").click()
    cy.wait(2500)
    cy.get('input[role="combobox"]').click()
    cy.contains(" 2023-03-29 | 17:45 | ME0368 | BEY → JED ").click()
    cy.get('input[id="passengerName"]').type("Toni Kiwan")
    cy.get('input[id="requestedBy"]').type("Lara")
    cy.get('textarea[id="item"]').type("American Coffee")
    cy.contains("Cash").click()
    cy.contains("Received").click()
    cy.contains("Save").click()
  })
})