// describe('testing Payment method', () => {
//   it('Click on flight date and change payment method should be saved', () => {
//     cy.visit(' https://itxi-recruiter-extract.web.app/login')
//     cy.contains('MEA Crewtablet Portal v1.29.0 (1880)')
//     cy.get('input[type="email"]').type("qaquiz@gmail.com")
//     cy.get('input[type="password"]').type("Test@123")
//     cy.contains('Login').click()
//     cy.wait(2000)
//     cy.contains("Awaiting Approvals").click()
//     cy.wait(5000)
//     cy.contains("2023-03-31").click()
//     cy.wait(5000)
//     // cy.get('input[id="rdCreditCard"]').click()
//     cy.contains("Credit Card").click()
//     cy.contains("Save").click()
//     cy.contains("Flight Date")
//   })
// })
// describe('testing payment method with payment status', () => {
//   it('Change in Payment method with Change in payment status', () => {
//     cy.visit(' https://itxi-recruiter-extract.web.app/login')
//     cy.get('input[type="email"]').type("qaquiz@gmail.com")
//     cy.get('input[type="password"]').type("Test@123")
//     cy.contains('Login').click()
//     cy.wait(2000)
//     cy.contains("Awaiting Approvals").click()
//     cy.wait(5000)
//     cy.contains("2023-03-31").click()
//     cy.wait(5000)
//     cy.contains("Credit Card").click()
//     cy.contains("Received").click()
//     cy.contains("Save").click()
//     cy.contains("Flight Date")
//   })
// })
describe('testing Payment method', () => {
  it('Click on flight date and change payment method should be saved', () => {
    cy.visit(' https://itxi-recruiter-extract.web.app/login')
    cy.get('input[type="email"]').type("qaquiz@gmail.com")
    cy.get('input[type="password"]').type("Test@123")
    cy.contains('Login').click()
    cy.wait(2000)
    cy.contains("Awaiting Approvals").click()
    cy.wait(5000)
    cy.contains("2023-03-31").click()
    cy.wait(5000)
    // cy.get('input[id="rdCreditCard"]').click()
    cy.contains("Complimentary").click()
    cy.contains("Save").click()
    cy.contains("Flight Date")
  })
})